version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: sales_raw
        columns:
          - name: '"Store"'
            tests: [not_null]
          - name: '"Date"'
            tests: [not_null]

      - name: stores_raw
        columns:
          - name: '"Store"'
            tests: [not_null, unique]



