version: 2

models:
  - name: dim_store
    columns:
      - name: store_id
        tests: [not_null, unique]

  - name: dim_date
    columns:
      - name: date_day
        tests: [not_null, unique]

  - name: fct_daily_sales
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: ['store_id', 'date_day']

    columns:
      - name: store_id
        tests: [not_null]
      - name: date_day
        tests: [not_null]
      - name: sales
        tests: [not_null]
      - name: customers
        tests: [not_null]

  - name: fct_weekly_sales
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: ['store_id', 'year_week']

    columns:
      - name: store_id
        tests: [not_null]
      - name: year_week
        tests: [not_null]
