version: 2

models:
  - name: int_sales_enriched
    tests:
      - dbt_utils.unique_combination_of_columns:
         arguments:
           combination_of_columns: ['store_id', 'date_day']
    columns:
      - name: store_id
        tests: [not_null]
      - name: date_day
        tests: [not_null]
